ALTER PROCEDURE LIST_COBRANZA_CUOTAS (
  PFECHA_DESDE DATE,
  PFECHA_HASTA DATE,
  PTRAER_CUOTAS_IMPAGAS SMALLINT,
  PFECHA_HISTORICA DATE
)
RETURNS (
  ORIGEN VARCHAR(50),
  COD_CONFIGURACION INTEGER,
  CUOTA INTEGER,
  PAGO INTEGER,
  TOTAL NUMERIC(12, 3),
  CANTIDAD INTEGER,
  TOTAL_PAGADO_HASTA_FECHA NUMERIC(12, 3),
  TOTAL_PAGADO_ADELANTO NUMERIC(12, 3),
  CANTIDAD_PAGADO INTEGER,
  FECHA_PAGO DATE,
  COD_MOVIMIENTO_FONDO INTEGER,
  FECHA_CUOTA DATE,
  FECHA_HASTA DATE,
  FECHA_VENCIMIENTO DATE,
  DESCRIPCION_CONFIG VARCHAR(200),
  FECHA_INICIO DATE,
  FECHA_BAJA DATE,
  COD_SUCURSAL INTEGER,
  EMPRESA_CONFIG VARCHAR(100),
  NRO_COMP_FACTURACION VARCHAR(15),
  NOMBRE VARCHAR(100),
  NRO_DOCUMENTO VARCHAR(50),
  SUCURSAL VARCHAR(80),
  MOV_CONCEPTO VARCHAR(100),
  MOV_USUARIO VARCHAR(100),
  MOV_EMPRESA VARCHAR(100),
  CATEGORIA VARCHAR(50),
  ZONA_COBRANZA_CONFIG VARCHAR(100),
  MEDIO_COBRO_CUOTA VARCHAR(100),
  COD_TALONARIO_FACTURA INTEGER,
  MESANO_CUOTA VARCHAR(10),
  GESTOR_CLIENTE VARCHAR(100),
  ESTADO_CUOTA_PERIODICA VARCHAR(50),
  VENDEDOR VARCHAR(100),
  JEFE_VENTA VARCHAR(100),
  GERENCIA VARCHAR(100),
  COD_VENDEDOR INTEGER,
  CANTIDAD_TOTAL_CUOTAS INTEGER,
  COBRADOR VARCHAR(100),
  MODALIDAD VARCHAR(100),
  PORC_COBRANZA NUMERIC(15, 6),
  PORC_VENTA NUMERIC(15, 6),
  COD_COBRADOR INTEGER,
  COMISION_COBRANZA NUMERIC(13, 3),
  COMISION_VENDEDOR NUMERIC(13, 3),
  CONCEPTO VARCHAR(500),
  DIRECCION VARCHAR(500),
  NRO_COMPROBANTE_IMPUTACION VARCHAR(15),
  TIPO_COMPROBANTE_IMPUTACION VARCHAR(50),
  NRO_COMPROBANTE_EMISION VARCHAR(15),
  NRO_COMPROBANTE_FACTURACION VARCHAR(15),
  PROPUESTA INTEGER,
  COD_PROPUESTA INTEGER  ,
  CATEGORIA_CLIENTE VARCHAR(50),
  COBRADOR_CUOTA VARCHAR(100),
  ENTRO SMALLINT,
  TIPO_PROPUESTA VARCHAR(100),
  NRO_COMPROBANTE_RENDICION VARCHAR(15),
  FECHA_COMPR_RENDICION DATE

)
AS
    DECLARE VARIABLE COD_COBRADOR_CUOTA INTEGER;
    DECLARE VARIABLE COD_MEDIO_COBRO_CUOTA INTEGER;
    DECLARE VARIABLE COD_MEDIO_COBRO INTEGER;
    DECLARE VARIABLE SERVICIO varchar(100);
    DECLARE VARIABLE COD_DOMICILIO INTEGER;
    DECLARE VARIABLE COD_TALONARIO_IMPUTACION INTEGER;
    DECLARE VARIABLE COD_TABULACION INTEGER;
    DECLARE VARIABLE COD_TALONARIO_FACTURACION INTEGER;
    DECLARE VARIABLE COD_TALONARIO_EMISION INTEGER;

BEGIN
--Inicalmente esto fue echo para ver solo las cuotas periodcas Cobradas en un en periodo
    IF  ((:PFECHA_DESDE= '01/01/1900')   and (:PFECHA_hasta= '01/01/1900')) then
    begin
    exit ;
    END
    CANTIDAD_TOTAL_CUOTAS = 1;
    FOR
        SELECT f.COD_MEDIO_COBRO ,  'CUOTAS_PERIODICAS', U.COD_CONFIGURACION, U.CUOTA, U.PAGO, U.TOTAL, COALESCE(U.FECHA_RENDICION, U.FECHA_PAGO)
        , U.COD_MOVIMIENTO_FONDO, U.FECHA_CUOTA, U.FECHA_HASTA, U.FECHA_VENCIMIENTO, U.NRO_COMPROBANTE_FACTURACION
        , U.COD_TALONARIO_FACTURACION, U.COD_TALONARIO_IMPUTACION, U.NRO_COMPROBANTE_IMPUTACION
        , F.DESCRIPCION, F.FECHA_INICIO, F.FECHA_BAJA, F.COD_SUCURSAL
        , CL.NOMBRE, CL.NRO_DOCUMENTO
        , CAT.CATEGORIA, 1, EDO.ESTADO
        , (SELECT NOMBRE FROM GESTORES_COBRANZAS  GE WHERE GE.COD_GESTOR=CL.COD_GESTOR),
        COALESCE( (SELECT E.RAZON_SOCIAL
        FROM TIPOS_COMPROBANTES T
        INNER JOIN EMPRESAS E ON E.COD_EMPRESA = T.COD_EMPRESA
         WHERE T.COD_TIPO_COMPROBANTE = f.COD_TIPO_COMPROBANTE_FACTURA),'')   , F.COD_VENDEDOR
        , U.COD_TALONARIO_FACTURACION , U.NRO_COMPROBANTE_FACTURACION
        ,COALESCE(CL.COD_DOMICILIO, CL.COD_DOMICILIO_POSTAL, CL.COD_DOMICILIO_LABORAL),
        U.COD_TALONARIO_EMISION, U.NRO_COMPROBANTE_EMISION,
        F.COD_PROPUESTA,
        (SELECT P.LEGAJO FROM PROPUESTA P WHERE P.COD_PROPUESTA = F.COD_PROPUESTA)
         , CATCLI.CATEGORIA ,
        (SELECT N.TIPO_COMPROBANTE   FROM TIPOS_COMPROBANTES N INNER JOIN COMPROBANTES M ON M.COD_TIPO_COMPROBANTE=
        N.COD_TIPO_COMPROBANTE WHERE M.COD_TALONARIO=U.COD_TALONARIO_IMPUTACION AND U.NRO_COMPROBANTE_IMPUTACION=
        M.NRO_COMPROBANTE)
        FROM CUOTAS_PERIODICAS U
        INNER JOIN CONFIG_CUOTAS_PERIODICAS F ON U.COD_CONFIGURACION=F.COD_CONFIGURACION
        INNER JOIN CLIENTES CL ON F.COD_CLIENTE=CL.COD_CLIENTE
        INNER JOIN CAT_CUOTAS_PERIODICAS CAT ON F.COD_CAT_CUOTA_PERIODICA=CAT.COD_CAT_CUOTA_PERIODICA
        INNER JOIN ESTADOS_DEUDAS EDO ON F.COD_ESTADO_DEUDA=EDO.COD_ESTADO_DEUDA
         INNER JOIN CAT_CLIENTES CATCLI ON CL.COD_CAT_CLIENTE=CATCLI.COD_CAT_CLIENTE
--        INNER JOIN MEDIOS_COBROS M ON F.COD_MEDIO_COBRO = M.COD_MEDIO_COBRO
        WHERE --edo.ACTIVA = 1 and

              U.ANULADO <> 1 AND  u.FECHA_CUOTA >= COALESCE( f.SUSPENDIDO_HASTA,'01/01/1970')  and
        U.FECHA_RENDICION BETWEEN :PFECHA_DESDE AND :PFECHA_HASTA
            OR
            ( U.FECHA_PAGO BETWEEN :PFECHA_DESDE AND :PFECHA_HASTA AND U.FECHA_RENDICION IS NULL)
        INTO  :COD_MEDIO_COBRO, :ORIGEN, :COD_CONFIGURACION, :CUOTA, :PAGO, :TOTAL_PAGADO_HASTA_FECHA , :FECHA_PAGO
        , :COD_MOVIMIENTO_FONDO, :FECHA_CUOTA, :FECHA_HASTA, :FECHA_VENCIMIENTO, :NRO_COMP_FACTURACION
        , :COD_TALONARIO_FACTURA, :COD_TALONARIO_IMPUTACION, :NRO_COMPROBANTE_IMPUTACION
        , :DESCRIPCION_CONFIG, :FECHA_INICIO, :FECHA_BAJA, :COD_SUCURSAL
        , :NOMBRE, :NRO_DOCUMENTO
        , :CATEGORIA, :CANTIDAD_PAGADO , :ESTADO_CUOTA_PERIODICA
        , :GESTOR_CLIENTE, :EMPRESA_CONFIG  , :COD_VENDEDOR
          , :COD_TALONARIO_FACTURACION ,    :NRO_COMPROBANTE_FACTURACION , :COD_DOMICILIO   ,
          :COD_TALONARIO_EMISION, :NRO_COMPROBANTE_EMISION
          ,:COD_PROPUESTA, :PROPUESTA  ,:CATEGORIA_CLIENTE, :TIPO_COMPROBANTE_IMPUTACION

    DO
    BEGIN

      ZONA_COBRANZA_CONFIG = null;
      COBRADOR = null;
      MODALIDAD = null;
      PORC_COBRANZA = 0;
      COD_COBRADOR =NULL;

      select list(s.DESCRIPCION, '')  from CUOTAS_PERIODICAS_SERVICIOS    c
      inner join ARTICULOS s on s.COD_ARTICULO=c.COD_SERVICIO
      where c.COD_CONFIGURACION=:cod_configuracion
      into :servicio;

      CONCEPTO=:SERVICIO ;

      SELECT DIRECCION||'-'||LOCALIDAD FROM DOMICILIO_SIMPLE(:COD_DOMICILIO)
      INTO :DIRECCION  ;

      select ZONA_COBRANZA, COBRADOR, MODALIDAD,     COD_COBRADOR , DETALLE
      from LUGAR_COBRO_SEGUN_MEDIO(:COD_MEDIO_COBRO)
      INTO :ZONA_COBRANZA_CONFIG, :COBRADOR, :MODALIDAD,     :COD_COBRADOR, :DIRECCION;
      COD_COBRADOR_CUOTA=NULL;
      IF (:NRO_COMPROBANTE_EMISION IS NOT NULL) THEN
        BEGIN
        SELECT first 1 CC.COD_COBRADOR
        FROM COMPROBANTES_CARGOS C
        INNER JOIN COBRADORES CC ON CC.COD_COBRADOR = C.COD_COBRADOR
        INNER JOIN DET_COMPROBANTES_CARGOS D ON D.COD_COMPROBANTE_CARGO = C.COD_COMPROBANTE_CARGO
        WHERE D.NRO_COMPROBANTE_ASIGNADO = :NRO_COMPROBANTE_EMISION
        AND D.COD_TALONARIO_ASIGNADO = :COD_TALONARIO_EMISION
        AND D.FECHA_IMPUTACION IS NOT NULL
        order by c.COD_COMPROBANTE_CARGO desc
        INTO :COD_COBRADOR_CUOTA;
        END
        ELSE
        BEGIN
            select (select  COD_COBRADOR from LUGAR_COBRO_SEGUN_MEDIO(c.COD_MEDIO_COBRO))
            from COMPROBANTES c
            where c.COD_TALONARIO=:COD_TALONARIO_IMPUTACION
            and c.NRO_COMPROBANTE=:NRO_COMPROBANTE_IMPUTACION
            INTO :COD_COBRADOR_CUOTA;

            IF(:COD_COBRADOR_CUOTA IS NULL ) THEN
            BEGIN
                SELECT first 1 CC.COD_COBRADOR
                FROM COMPROBANTES_CARGOS C
                INNER JOIN COBRADORES CC ON CC.COD_COBRADOR = C.COD_COBRADOR
                INNER JOIN DET_COMPROBANTES_CARGOS D ON D.COD_COMPROBANTE_CARGO = C.COD_COMPROBANTE_CARGO
                WHERE D.NRO_COMPROBANTE_ASIGNADO = :NRO_COMPROBANTE_FACTURACION
                AND D.COD_TALONARIO_ASIGNADO = :COD_TALONARIO_FACTURACION
                order by c.COD_COMPROBANTE_CARGO desc
                INTO :COD_COBRADOR_CUOTA;
            END
        END

      if ((:COD_COBRADOR_CUOTA IS NOT NULL)) THEN
      BEGIN
      IF(:COD_COBRADOR <> :COD_COBRADOR_CUOTA) THEN
        BEGIN
          COD_COBRADOR = :COD_COBRADOR_CUOTA;
          SELECT C.NOMBRE
          FROM COBRADORES C
          WHERE C.COD_COBRADOR = :COD_COBRADOR_CUOTA
          INTO :COBRADOR;
        END
      END

      SELECT FIRST 1 CO.NRO_COMPROBANTE,CO.FECHA
      FROM CTA_CTE_COBRADORES C
      INNER JOIN DET_CTA_CTE_COBRADORES D ON D.COD_TALONARIO = C.COD_TALONARIO AND D.NRO_COMPROBANTE=C.NRO_COMPROBANTE
      INNER JOIN COMPROBANTES CO ON CO.COD_TALONARIO=D.COD_TALONARIO AND CO.NRO_COMPROBANTE=D.NRO_COMPROBANTE
      WHERE ((D.NRO_COMPROBANTE_RENDIDO = :NRO_COMPROBANTE_FACTURACION
      AND D.COD_TALONARIO_RENDIDO = :COD_TALONARIO_FACTURACION )
      OR   (D.NRO_COMPROBANTE_RENDIDO = :NRO_COMPROBANTE_IMPUTACION
      AND D.COD_TALONARIO_RENDIDO = :COD_TALONARIO_IMPUTACION )
      OR   (D.NRO_COMPROBANTE_RENDIDO = :NRO_COMPROBANTE_EMISION
      AND D.COD_TALONARIO_RENDIDO = :COD_TALONARIO_EMISION ))
      INTO :NRO_COMPROBANTE_RENDICION, :FECHA_COMPR_RENDICION;

      SELECT C.COMISION
      FROM COBRADORES C
      WHERE C.COD_COBRADOR = :COD_COBRADOR
      INTO :PORC_COBRANZA;

      COMISION_COBRANZA = :TOTAL_PAGADO_HASTA_FECHA * :PORC_COBRANZA /100;

      VENDEDOR ='';
      JEFE_VENTA  ='';
      GERENCIA  ='';

      SELECT GERENCIA ,JEFE_EQUIPO ,VENDEDOR   ,COD_TABULACION
      FROM PROC_DATOS_VENDEDOR (:COD_VENDEDOR)
      INTO :GERENCIA ,:JEFE_VENTA, :VENDEDOR , :COD_TABULACION;


      COMISION_VENDEDOR = 0;

      SELECT SALIDA
      FROM PROC_EVALUAR_TABUL_SOLO_SAL(:COD_TABULACION, :CUOTA)
      INTO :PORC_VENTA;

      COMISION_VENDEDOR = :PORC_VENTA * :TOTAL_PAGADO_HASTA_FECHA /100;


      if (:FECHA_VENCIMIENTO <=:PFECHA_HASTA) THEN
      BEGIN
          TOTAL = :TOTAL_PAGADO_HASTA_FECHA ;
      END
      ELSE
      BEGIN
          TOTAL = 0;
      END


      TOTAL_PAGADO_ADELANTO =0;
      IF (:FECHA_VENCIMIENTO > :PFECHA_HASTA) THEN
        BEGIN
          TOTAL_PAGADO_ADELANTO = :TOTAL_PAGADO_HASTA_FECHA;
          TOTAL_PAGADO_HASTA_FECHA =0;
        END


       MOV_CONCEPTO= NULL;
       MOV_USUARIO= NULL;
       MOV_EMPRESA= NULL;
       SUCURSAL= NULL;
--        EMPRESA_CONFIG= NULL;
       MEDIO_COBRO_CUOTA= NULL;
       MESANO_CUOTA=NULL;

       SELECT S.NOMBRE
        FROM SUCURSALES S
  --      LEFT JOIN EMPRESAS E ON S.COD_EMPRESA=E.COD_EMPRESA
        WHERE S.COD_SUCURSAL=:COD_SUCURSAL
        INTO :SUCURSAL;

       MEDIO_COBRO_CUOTA = NULL;

        SELECT M.CONCEPTO, A.ALIAS, E.RAZON_SOCIAL FROM MOVIMIENTOS_FONDOS M
        INNER JOIN TIPOS_COMPROBANTES TC ON M.COD_TIPO_COMPROBANTE=TC.COD_TIPO_COMPROBANTE
        INNER JOIN EMPRESAS E ON TC.COD_EMPRESA = E.COD_EMPRESA
        LEFT JOIN USUARIOS A ON M.COD_USUARIO_CREO=A.COD_USUARIO
        WHERE M.COD_MOVIMIENTO_FONDO=:COD_MOVIMIENTO_FONDO
        INTO :MOV_CONCEPTO, :MOV_USUARIO, :MOV_EMPRESA;

        MESANO_CUOTA=EXTRACT(YEAR FROM :FECHA_VENCIMIENTO) || LPAD(EXTRACT(MONTH FROM :FECHA_VENCIMIENTO), 2,'0');
        SUSPEND;
    END
    ORIGEN=NULL; COD_CONFIGURACION=NULL;CUOTA=NULL;PAGO=NULL;TOTAL=NULL;FECHA_PAGO=NULL;
        COD_MOVIMIENTO_FONDO=NULL;FECHA_CUOTA=NULL;FECHA_HASTA=NULL;FECHA_VENCIMIENTO=NULL;NRO_COMP_FACTURACION=NULL;
        DESCRIPCION_CONFIG=NULL;FECHA_INICIO=NULL;FECHA_BAJA=NULL;COD_SUCURSAL=NULL;
        NOMBRE=NULL;NRO_DOCUMENTO=NULL;
        CATEGORIA=NULL;         COD_VENDEDOR = NULL;
        CANTIDAD=NULL;             COMISION_COBRANZA = 0;
        MEDIO_COBRO_CUOTA= NULL;
        COD_MEDIO_COBRO_CUOTA= NULL; GESTOR_CLIENTE = NULL; ESTADO_CUOTA_PERIODICA=NULL;  CONCEPTO=NULL;
        NRO_COMPROBANTE_RENDICION=NULL; FECHA_COMPR_RENDICION=NULL;
   FOR
        SELECT f.COD_MEDIO_COBRO,  'CREDITOS', U.COD_CREDITO, U.CUOTA, U.PAGO, U.TOTAL, COALESCE(U.FECHA_RENDICION, U.FECHA_PAGO)
        , U.COD_MOVIMIENTO_FONDO, NULL, NULL, U.FECHA_VENCIMIENTO, U.NRO_COMPROBANTE_FACTURACION
        , U.COD_MEDIO_COBRO, U.COD_TALONARIO_IMPUTACION, U.NRO_COMPROBANTE_IMPUTACION
        , F.DESCRIPCION, F.FECHA_INICIO, F.FECHA_BAJA, F.COD_SUCURSAL
        , CL.NOMBRE, CL.NRO_DOCUMENTO, 1, EDO.ESTADO
        , (SELECT NOMBRE FROM GESTORES_COBRANZAS  GE WHERE GE.COD_GESTOR=CL.COD_GESTOR),
        COALESCE( (SELECT E.RAZON_SOCIAL
        FROM TIPOS_COMPROBANTES T
        INNER JOIN EMPRESAS E ON E.COD_EMPRESA = T.COD_EMPRESA
        WHERE T.COD_TIPO_COMPROBANTE = f.COD_TIPO_COMPROBANTE_FACTURA),'')
        , U.COD_TALONARIO_FACTURACION , U.NRO_COMPROBANTE_FACTURACION  , COALESCE(CL.COD_DOMICILIO, CL.COD_DOMICILIO_POSTAL, CL.COD_DOMICILIO_LABORAL)
        , U.COD_TALONARIO_emision , U.NRO_COMPROBANTE_EMISION, F.COD_PROPUESTA,
        (SELECT P.LEGAJO FROM PROPUESTA P WHERE P.COD_PROPUESTA = F.COD_PROPUESTA)
        ,     CATCLI.CATEGORIA,
        (SELECT N.TIPO_COMPROBANTE   FROM TIPOS_COMPROBANTES N INNER JOIN COMPROBANTES M ON M.COD_TIPO_COMPROBANTE=
        N.COD_TIPO_COMPROBANTE WHERE M.COD_TALONARIO=U.COD_TALONARIO_IMPUTACION AND U.NRO_COMPROBANTE_IMPUTACION=
        M.NRO_COMPROBANTE)
        FROM CUOTAS U
        INNER JOIN CREDITOS F ON U.COD_CREDITO=F.COD_CREDITO
        INNER JOIN CLIENTES CL ON F.COD_CLIENTE=CL.COD_CLIENTE
        INNER JOIN ESTADOS_DEUDAS EDO ON F.COD_ESTADO_DEUDA=EDO.COD_ESTADO_DEUDA
        INNER JOIN CAT_CLIENTES CATCLI ON CL.COD_CAT_CLIENTE=CATCLI.COD_CAT_CLIENTE
--        INNER JOIN MEDIOS_COBROS M ON F.COD_MEDIO_COBRO = M.COD_MEDIO_COBRO
        WHERE U.ANULADO <> 1 AND U.FECHA_RENDICION BETWEEN :PFECHA_DESDE AND :PFECHA_HASTA
            OR
            ( U.FECHA_PAGO BETWEEN :PFECHA_DESDE AND :PFECHA_HASTA AND U.FECHA_RENDICION IS NULL)

        INTO  :COD_MEDIO_COBRO, :ORIGEN, :COD_CONFIGURACION, :CUOTA, :PAGO, :TOTAL_PAGADO_HASTA_FECHA , :FECHA_PAGO
        , :COD_MOVIMIENTO_FONDO, :FECHA_CUOTA, :FECHA_HASTA, :FECHA_VENCIMIENTO, :NRO_COMP_FACTURACION
        , :COD_MEDIO_COBRO_CUOTA, :COD_TALONARIO_IMPUTACION, :NRO_COMPROBANTE_IMPUTACION
        , :DESCRIPCION_CONFIG, :FECHA_INICIO, :FECHA_BAJA, :COD_SUCURSAL,
         :NOMBRE, :NRO_DOCUMENTO, :CANTIDAD_PAGADO , :ESTADO_CUOTA_PERIODICA
        , :GESTOR_CLIENTE, :EMPRESA_CONFIG             , :COD_TALONARIO_FACTURACION ,    :NRO_COMPROBANTE_FACTURACION   , :COD_DOMICILIO
         ,:COD_TALONARIO_EMISION ,    :NRO_COMPROBANTE_EMISION
        ,  :COD_PROPUESTA, :PROPUESTA  ,:CATEGORIA_CLIENTE,:TIPO_COMPROBANTE_IMPUTACION

    DO
    BEGIN

      ZONA_COBRANZA_CONFIG = null;
      COBRADOR = null;
      MODALIDAD = null;
      PORC_COBRANZA = 0;
      COD_COBRADOR =NULL;



      SELECT DIRECCION||'-'||LOCALIDAD FROM DOMICILIO_SIMPLE(:COD_DOMICILIO)
      INTO :DIRECCION  ;

      select ZONA_COBRANZA, COBRADOR, MODALIDAD,     COD_COBRADOR , DETALLE
      from LUGAR_COBRO_SEGUN_MEDIO(:COD_MEDIO_COBRO)
      INTO :ZONA_COBRANZA_CONFIG, :COBRADOR, :MODALIDAD,     :COD_COBRADOR, :DIRECCION;

      COD_COBRADOR_CUOTA=null;
      IF (:NRO_COMPROBANTE_EMISION IS NOT NULL) THEN
        BEGIN
        SELECT first 1 CC.COD_COBRADOR
        FROM COMPROBANTES_CARGOS C
        INNER JOIN COBRADORES CC ON CC.COD_COBRADOR = C.COD_COBRADOR
        INNER JOIN DET_COMPROBANTES_CARGOS D ON D.COD_COMPROBANTE_CARGO = C.COD_COMPROBANTE_CARGO
        WHERE D.NRO_COMPROBANTE_ASIGNADO = :NRO_COMPROBANTE_EMISION
        AND D.COD_TALONARIO_ASIGNADO = :COD_TALONARIO_EMISION
        AND D.FECHA_IMPUTACION IS NOT NULL
        order by c.COD_COMPROBANTE_CARGO desc
        INTO :COD_COBRADOR_CUOTA;

        END
        ELSE
        BEGIN
            IF (:NRO_COMPROBANTE_IMPUTACION IS NOT NULL  and :NRO_COMPROBANTE_IMPUTACION<>'') THEN
            begin
              select (select  COD_COBRADOR from LUGAR_COBRO_SEGUN_MEDIO(c.COD_MEDIO_COBRO))
              from COMPROBANTES c
              where c.COD_TALONARIO=:COD_TALONARIO_IMPUTACION
              and c.NRO_COMPROBANTE=:NRO_COMPROBANTE_IMPUTACION
              INTO :COD_COBRADOR_CUOTA;
            end

            IF(:COD_COBRADOR_CUOTA IS NULL ) THEN
            BEGIN
                IF (:NRO_COMPROBANTE_FACTURACION IS NOT NULL and :NRO_COMPROBANTE_FACTURACION<>'' ) THEN
                begin
                  SELECT first 1 CC.COD_COBRADOR
                  FROM COMPROBANTES_CARGOS C
                  INNER JOIN COBRADORES CC ON CC.COD_COBRADOR = C.COD_COBRADOR
                  INNER JOIN DET_COMPROBANTES_CARGOS D ON D.COD_COMPROBANTE_CARGO = C.COD_COMPROBANTE_CARGO
                  WHERE D.NRO_COMPROBANTE_ASIGNADO = :NRO_COMPROBANTE_FACTURACION
                  AND D.COD_TALONARIO_ASIGNADO = :COD_TALONARIO_FACTURACION
                  order by c.COD_COMPROBANTE_CARGO desc
                  INTO :COD_COBRADOR_CUOTA;
                end
            END
        END

      if  ( (:COD_COBRADOR_CUOTA IS NOT NULL)  ) THEN
      BEGIN
      IF(:COD_COBRADOR <> :COD_COBRADOR_CUOTA) THEN
        BEGIN
          COD_COBRADOR = :COD_COBRADOR_CUOTA;
          SELECT C.NOMBRE
          FROM COBRADORES C
          WHERE C.COD_COBRADOR = :COD_COBRADOR_CUOTA
          INTO :COBRADOR;
        END
      END

           SELECT FIRST 1 CO.NRO_COMPROBANTE,CO.FECHA
      FROM CTA_CTE_COBRADORES C
      INNER JOIN DET_CTA_CTE_COBRADORES D ON D.COD_TALONARIO = C.COD_TALONARIO AND D.NRO_COMPROBANTE=C.NRO_COMPROBANTE
      INNER JOIN COMPROBANTES CO ON CO.COD_TALONARIO=D.COD_TALONARIO AND CO.NRO_COMPROBANTE=D.NRO_COMPROBANTE
      WHERE ((D.NRO_COMPROBANTE_RENDIDO = :NRO_COMPROBANTE_FACTURACION
      AND D.COD_TALONARIO_RENDIDO = :COD_TALONARIO_FACTURACION )
      OR   (D.NRO_COMPROBANTE_RENDIDO = :NRO_COMPROBANTE_IMPUTACION
      AND D.COD_TALONARIO_RENDIDO = :COD_TALONARIO_IMPUTACION )
      OR   (D.NRO_COMPROBANTE_RENDIDO = :NRO_COMPROBANTE_EMISION
      AND D.COD_TALONARIO_RENDIDO = :COD_TALONARIO_EMISION ))
      INTO :NRO_COMPROBANTE_RENDICION, :FECHA_COMPR_RENDICION;

      SELECT C.COMISION
      FROM COBRADORES C
      WHERE C.COD_COBRADOR = :COD_COBRADOR
      INTO :PORC_COBRANZA;



      COMISION_COBRANZA = :TOTAL_PAGADO_HASTA_FECHA * :PORC_COBRANZA /100;

      VENDEDOR ='';
      JEFE_VENTA  ='';
      GERENCIA  ='';
      COD_VENDEDOR = NULL;

      SELECT VENDEDOR ,JEFE_VENTA ,GERENCIA_VENTA ,COD_VENDEDOR   , COD_TABULACION
      FROM PROC_VENDEDOR_DE_CREDITO(:COD_CONFIGURACION)
      INTO :VENDEDOR ,:JEFE_VENTA ,:GERENCIA, :COD_VENDEDOR, :COD_TABULACION;
      COMISION_VENDEDOR = 0;

      SELECT SALIDA
      FROM PROC_EVALUAR_TABUL_SOLO_SAL(:COD_TABULACION,:CUOTA)
      INTO :PORC_VENTA;

      COMISION_VENDEDOR = :PORC_VENTA * :TOTAL_PAGADO_HASTA_FECHA/100;




        MOV_CONCEPTO= NULL;
        MOV_USUARIO= NULL;
        MOV_EMPRESA= NULL;
        SUCURSAL= NULL;
        --EMPRESA_CONFIG= NULL;
        MEDIO_COBRO_CUOTA= NULL;
        MESANO_CUOTA=NULL;

        if (:FECHA_VENCIMIENTO <= :PFECHA_HASTA) THEN
        BEGIN
          TOTAL = :TOTAL_PAGADO_HASTA_FECHA;
        END
        ELSE
        BEGIN
          TOTAL = 0;
        END

        TOTAL_PAGADO_ADELANTO =0;
        IF (:FECHA_VENCIMIENTO > :PFECHA_HASTA) THEN
        BEGIN
          TOTAL_PAGADO_ADELANTO = :TOTAL_PAGADO_HASTA_FECHA;
          TOTAL_PAGADO_HASTA_FECHA =0;
        END


        SELECT S.NOMBRE
        FROM SUCURSALES S
--        LEFT JOIN EMPRESAS E ON S.COD_EMPRESA=E.COD_EMPRESA
        WHERE S.COD_SUCURSAL=:COD_SUCURSAL
        INTO :SUCURSAL;


        select (select   ZONA_COBRANZA from LUGAR_COBRO_SEGUN_MEDIO(c.COD_MEDIO_COBRO))
        from COMPROBANTES c where c.COD_TALONARIO=:COD_TALONARIO_IMPUTACION and c.NRO_COMPROBANTE=:NRO_COMPROBANTE_IMPUTACION
        INTO :MEDIO_COBRO_CUOTA;

        COD_COBRADOR_CUOTA =NULL;
        IF(:MEDIO_COBRO_CUOTA IS NULL ) THEN
        BEGIN
          SELECT first 1 CC.COD_COBRADOR
          FROM COMPROBANTES_CARGOS C
          INNER JOIN COBRADORES CC ON CC.COD_COBRADOR = C.COD_COBRADOR
          INNER JOIN DET_COMPROBANTES_CARGOS D ON D.COD_COMPROBANTE_CARGO = C.COD_COMPROBANTE_CARGO
          WHERE D.NRO_COMPROBANTE_ASIGNADO = :NRO_COMPROBANTE_FACTURACION
          AND D.COD_TALONARIO_ASIGNADO = :COD_TALONARIO_FACTURACION
          order by c.COD_COMPROBANTE_CARGO desc
          INTO :COD_COBRADOR_CUOTA;

          SELECT C.NOMBRE
          FROM COBRADORES C
          WHERE C.COD_COBRADOR = :COD_COBRADOR_CUOTA
          INTO :MEDIO_COBRO_CUOTA;
        END
       /*
        IF(:COD_COBRADOR <> :COD_COBRADOR_CUOTA) THEN
        BEGIN
          COD_COBRADOR = :COD_COBRADOR_CUOTA;
        END
                */

        SELECT M.CONCEPTO, A.ALIAS, E.RAZON_SOCIAL FROM MOVIMIENTOS_FONDOS M
        INNER JOIN TIPOS_COMPROBANTES TC ON M.COD_TIPO_COMPROBANTE=TC.COD_TIPO_COMPROBANTE
        INNER JOIN EMPRESAS E ON TC.COD_EMPRESA = E.COD_EMPRESA
        LEFT JOIN USUARIOS A ON M.COD_USUARIO_CREO=A.COD_USUARIO
        WHERE M.COD_MOVIMIENTO_FONDO=:COD_MOVIMIENTO_FONDO
        INTO :MOV_CONCEPTO, :MOV_USUARIO, :MOV_EMPRESA;

        MESANO_CUOTA=EXTRACT(YEAR FROM :FECHA_VENCIMIENTO) || LPAD(EXTRACT(MONTH FROM :FECHA_VENCIMIENTO), 2,'0');
        SUSPEND;
    END
