<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <style>
@import url('//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css');
.date-form { margin: 10px; }
label.control-label span { cursor: pointer; }
</style>
<h1>Camaras</h1>
<hr/>
<div align="right" class="form-group"> 
<div class="col-sm-12"> 
<form name="a" method="post" action="">
<input type="button"  name="new_camara" value="New" class="btn btn-primary" onclick="window.location.assign('application/index/add')"/>
</form>
<br/>
<form name="b"  method="post" action="">
<select name="undelete_text">
<option value="">Select </option>
<?php foreach($this->undeletelist as $un){ ?>
<option value="<?php echo $un['id']; ?>"><?php echo $un['descripcion']; ?></option>
<?php } ?>
</select>
<input type="submit"  name="undelete_camara" value="Undelete" class="btn btn-warning"/>
</form>
</div> 
</div> 
<br/>
<hr/>
<div class="container">
  <table class="table  table-striped table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Tipo</th>
		<th>Est.</th>
        <th>Cod.</th>
        <th>Des.</th>
        <th>Pos.</th>
        <th>Ip</th>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Alta </th>
        <th>Alta F. </th>
        <th>Modif.</th>
        <th>Modif. F.</th>
        <th>Fecha baja</th>
        <th>Baja U.</th>
		<th></th>
		<th></th>
      </tr>
    </thead>
    <tbody>
<?php  foreach($this->camaras as $cam){
?>
<tr>
<td><?php echo $cam['id']; ?></td>
<td><?php echo $cam['tipo']; ?></td>
<td><?php echo $cam['estado']; ?></td>
<td><?php echo $cam['codigo']; ?></td>
<td><?php echo $cam['descripcion']; ?></td>
<td><?php echo $cam['posicion']; ?></td>
<td><?php echo $cam['ip']; ?></td>
<td><?php echo $cam['marca']; ?></td>
<td><?php echo $cam['modelo']; ?></td>
<td><?php echo $cam['altausuario']; ?></td>
<td><?php echo $cam['altafecha']; ?></td>
<td><?php echo $cam['modiusuario']; ?></td>
<td><?php echo $cam['modifecha']; ?></td>
<td><?php echo $cam['bajafecha']; ?></td>
<td><?php echo $cam['bajausuario']; ?></td>
<td>
<form action="" method="post">
<input type="hidden" name="edit_id" value="<?php echo $cam['id']; ?>">
<input type="submit" name="edit" value="Edit" class="btn btn-success" />
<!-- /application/index/edit -->
</form>
</td><td>
<form action="" method="post">
<input type="hidden" name="delete_id" value="<?php echo $cam['id']; ?>">
<input type="submit" id="<?php echo $cam['id']; ?>" name="Delete" value="Delete" class="btn btn-danger"/>
</form>
</td>
</tr>
<?php
}?>   
   
    </tbody>
  </table>
</div>
<br/><br/>
</div>
