<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class estadoCamara extends \Application\Entity\estadoCamara implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'nombre', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'descripcion', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'icono', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'altausuario', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'altafecha', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'modiusuario', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'modifecha', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'bajausuario', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'bajafecha', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'estadoregistro');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'nombre', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'descripcion', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'icono', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'altausuario', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'altafecha', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'modiusuario', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'modifecha', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'bajausuario', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'bajafecha', '' . "\0" . 'Application\\Entity\\estadoCamara' . "\0" . 'estadoregistro');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (estadoCamara $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($fn));

        return parent::setId($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($fn));

        return parent::setNombre($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($fn));

        return parent::setDescripcion($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcono($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcono', array($fn));

        return parent::setIcono($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcono', array());

        return parent::getIcono();
    }

    /**
     * {@inheritDoc}
     */
    public function setAltausuario($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAltausuario', array($fn));

        return parent::setAltausuario($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getAltausuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAltausuario', array());

        return parent::getAltausuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setAltafecha($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAltafecha', array($fn));

        return parent::setAltafecha($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getAltafecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAltafecha', array());

        return parent::getAltafecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setModiusuario($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModiusuario', array($fn));

        return parent::setModiusuario($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getModiusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModiusuario', array());

        return parent::getModiusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifecha($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifecha', array($fn));

        return parent::setModifecha($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifecha', array());

        return parent::getModifecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setBajausuario($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBajausuario', array($fn));

        return parent::setBajausuario($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getBajausuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBajausuario', array());

        return parent::getBajausuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setBajafecha($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBajafecha', array($fn));

        return parent::setBajafecha($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getBajafecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBajafecha', array());

        return parent::getBajafecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoregistro($fn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoregistro', array($fn));

        return parent::setEstadoregistro($fn);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoregistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoregistro', array());

        return parent::getEstadoregistro();
    }

}
