// <auto-generated />
namespace PCHI.PMS.MessageDataLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MessageSuccess_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageSuccess_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201410030237068_MessageSuccess_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
