// <auto-generated />
namespace PCHI.DataAccessLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class OriginalValue_RemovedFromAuditlog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OriginalValue_RemovedFromAuditlog));
        
        string IMigrationMetadata.Id
        {
            get { return "201411181639465_OriginalValue_RemovedFromAuditlog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
