// <auto-generated />
namespace PCHI.DataAccessLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Questionnaire_DisplayName_IntroductionMessages_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Questionnaire_DisplayName_IntroductionMessages_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201411040326138_Questionnaire_DisplayName_IntroductionMessages_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
