// <auto-generated />
namespace PCHI.DataAccessLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class PageTexts_Added_And_AuditLog_Enhanced : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageTexts_Added_And_AuditLog_Enhanced));
        
        string IMigrationMetadata.Id
        {
            get { return "201411200132515_PageTexts_Added_And_AuditLog_Enhanced"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
