// <auto-generated />
namespace PCHI.DataAccessLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RequiredRestrictionRemovedOn_ScheduleQuestionniareDate_In_QuestionnaireUserResponseGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequiredRestrictionRemovedOn_ScheduleQuestionniareDate_In_QuestionnaireUserResponseGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201409221659559_RequiredRestrictionRemovedOn_ScheduleQuestionniareDate_In_QuestionnaireUserResponseGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
