// <auto-generated />
namespace PCHI.DataAccessLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AttributesAddedTo_Item_Format : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttributesAddedTo_Item_Format));
        
        string IMigrationMetadata.Id
        {
            get { return "201410091813090_AttributesAddedTo_Item_Format"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
